'use client';
import dynamic from 'next/dynamic';
import {useEffect,useState,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,CalendarDays,Check,LockKeyhole,MapPinOff,Palette,Pause,Play,RotateCcw,Satellite} from 'lucide-react';
import AppDialog from '@/components/ui/AppDialog';
import {useGeolocation} from '@/hooks/useGeolocation';
import {useWakeLock} from '@/hooks/useWakeLock';
import {isInsideTerritory,totalDistance} from '@/lib/geoUtils';
import {getSupabase} from '@/lib/supabase';
import {draftKey,queueRoute,uploadRoute,type RouteDraft} from '@/lib/offlineRoutes';

const MapWrapper=dynamic(()=>import('@/components/map/MapWrapper'),{ssr:false});
function formatDuration(seconds:number){const minutes=Math.floor(seconds/60);return`${String(minutes).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}

export default function TrackerPage(){
  const router=useRouter();const tracker=useGeolocation();const wake=useWakeLock();
  const[seconds,setSeconds]=useState(0);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');
  const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[color,setColor]=useState('#eab02f');
  const[outsideDialog,setOutsideDialog]=useState<'continue'|'save'|null>(null);const[outsideAccepted,setOutsideAccepted]=useState(false);
  const [owner,setOwner]=useState(''),[draftReady,setDraftReady]=useState(false);const routeId=useRef('');const completed=useRef(false);
  useEffect(()=>{let alive=true;void getSupabase().auth.getSession().then(({data:{session}})=>{if(!alive)return;if(!session){router.replace('/login/');return}setOwner(session.user.id);routeId.current=crypto.randomUUID();try{const raw=localStorage.getItem(draftKey(session.user.id));if(raw){const draft=JSON.parse(raw) as RouteDraft;if(Array.isArray(draft.path)&&draft.path.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite))){routeId.current=draft.id;tracker.restore(draft.path);setSeconds(draft.seconds);setDate(draft.date);setColor(draft.color);setOutsideAccepted(draft.outsideAccepted);setMessage('Se recuperó tu recorrido sin guardar. Puedes continuarlo o finalizarlo.')}}}catch{setMessage('No se pudo recuperar el borrador local.')}setDraftReady(true)});return()=>{alive=false}},[router,tracker.restore]);
  useEffect(()=>{if(!draftReady||!owner||completed.current)return;try{if(tracker.path.length)localStorage.setItem(draftKey(owner),JSON.stringify({id:routeId.current,path:tracker.path,date,color,seconds,outsideAccepted}));else localStorage.removeItem(draftKey(owner))}catch{setMessage('No hay espacio para el respaldo local. Guarda tu recorrido antes de salir.')}},[draftReady,owner,tracker.path,date,color,seconds,outsideAccepted]);
  useEffect(()=>{if(tracker.status!=='tracking')return;const id=window.setInterval(()=>setSeconds(value=>value+1),1000);return()=>window.clearInterval(id)},[tracker.status]);
  useEffect(()=>{if(!tracker.currentPosition||outsideAccepted||outsideDialog||isInsideTerritory(tracker.currentPosition))return;tracker.pause();void wake.release();setOutsideDialog('continue')},[tracker.currentPosition,outsideAccepted,outsideDialog,tracker.pause,wake.release]);
  async function start(){if(!draftReady||saving)return;await wake.request();tracker.start()}
  async function pause(){tracker.pause();await wake.release()}
  async function persistRoute(){if(saving||!owner)return;if(tracker.path.length<2){setMessage('La ruta necesita al menos dos ubicaciones.');return}setSaving(true);const draft:RouteDraft={id:routeId.current,path:tracker.path,date,color,seconds,outsideAccepted};try{if(navigator.onLine)await uploadRoute(owner,draft);else queueRoute(owner,draft);completed.current=true;localStorage.removeItem(draftKey(owner));tracker.pause();await wake.release();router.replace('/dashboard/')}catch{setMessage('No se pudo guardar. Tu recorrido sigue en este dispositivo; inténtalo cuando tengas conexión.')}finally{setSaving(false)}}
  async function save(){if(tracker.path.some(point=>!isInsideTerritory(point))){setOutsideDialog('save');return}await persistRoute()}
  async function continueOutside(){setOutsideAccepted(true);setOutsideDialog(null);await start()}
  async function cancelOutside(){tracker.pause();await wake.release();router.push('/dashboard/')}
  async function goToDashboard(){tracker.pause();await wake.release();router.push('/dashboard/')}
  const distance=totalDistance(tracker.path);
  return <main className="relative h-dvh min-h-[36rem] overflow-hidden bg-[#dde7f4]">
    <MapWrapper currentPath={tracker.path} currentPathColor={color} currentPosition={tracker.currentPosition} restrictToTerritory={false}/>
    <header className="absolute inset-x-0 top-0 z-[500] flex items-center justify-between p-3 sm:p-5"><button className="focus-ring grid size-12 place-items-center rounded-2xl bg-white shadow-lg" onClick={goToDashboard} aria-label="Volver al mapa principal"><ArrowLeft/></button><div className="rounded-2xl bg-[#0c2347] px-4 py-3 text-center text-white shadow-lg"><p className="text-[12px] font-bold uppercase tracking-widest text-[#b8d0f7]">Modo Runner</p><p className="font-bold">Recorrido GPS</p></div><div className={`grid size-12 place-items-center rounded-2xl shadow-lg ${wake.active?'bg-[#2f63b8] text-white':'bg-white text-[#5f6f86]'}`} title={wake.active?'Pantalla protegida':'Wake Lock inactivo'}><LockKeyhole/></div></header>
    <section className="absolute inset-x-3 bottom-3 z-[500] mx-auto max-w-lg rounded-[1.75rem] border border-white/70 bg-white/95 p-4 shadow-2xl backdrop-blur sm:bottom-5">
      <p className="mb-2 text-xs text-[#5f6f86]">Borrador automático en este dispositivo. Sin conexión, las rutas finalizadas se enviarán al regresar al mapa con internet.</p>
      <div className="mb-3 grid grid-cols-3 divide-x divide-[#cfd9e8] text-center"><div><p className="text-[12px] font-bold uppercase tracking-wider text-[#5f6f86]">Distancia</p><b className="text-xl">{distance<1000?`${Math.round(distance)} m`:`${(distance/1000).toFixed(2)} km`}</b></div><div><p className="text-[12px] font-bold uppercase tracking-wider text-[#5f6f86]">Tiempo</p><b className="text-xl">{formatDuration(seconds)}</b></div><div><p className="text-[12px] font-bold uppercase tracking-wider text-[#5f6f86]">Precisión</p><b className="text-xl">{tracker.accuracy?`±${Math.round(tracker.accuracy)} m`:'—'}</b></div></div>
      <div className="mb-3 grid grid-cols-[1fr_auto] gap-3"><label className="text-sm font-bold"><span className="flex items-center gap-1.5"><CalendarDays size={15}/>Fecha</span><input className="mt-1 min-h-10 w-full rounded-xl border border-[#cfd9e8] px-3" type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label className="text-sm font-bold"><span className="flex items-center gap-1.5"><Palette size={15}/>Color</span><input className="mt-1 size-10 rounded-xl border border-[#cfd9e8] bg-white p-1" type="color" value={color} onChange={event=>setColor(event.target.value)}/></label></div>
      {(tracker.error||message)&&<p role="alert" className="mb-3 rounded-xl bg-[#fff0f2] p-3 text-sm font-semibold text-[#a61e37]">{tracker.error||message}</p>}
      <div className="flex gap-2">{tracker.status==='tracking'?<button className="focus-ring flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-[#f4b740] font-bold" onClick={pause}><Pause size={20}/>Pausar</button>:<button className="focus-ring flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-[#2f63b8] font-bold text-white" onClick={start}><Play size={20}/>{tracker.path.length?'Continuar':'Iniciar GPS'}</button>}<button className="focus-ring grid size-12 place-items-center rounded-xl bg-[#eef4fc]" onClick={()=>{tracker.reset();setSeconds(0);setOutsideAccepted(false)}} aria-label="Reiniciar"><RotateCcw size={20}/></button>{tracker.path.length>1&&<button className="focus-ring grid size-12 place-items-center rounded-xl bg-[#0c2347] text-white disabled:opacity-50" onClick={save} disabled={saving||tracker.status==='tracking'} aria-label="Guardar ruta"><Check size={21}/></button>}</div>
      <p className="mt-3 flex items-center justify-center gap-2 text-[13px] text-[#5f6f86]"><Satellite size={15}/>{wake.supported?'La pantalla se mantendrá encendida durante el recorrido.':'Mantén la pantalla encendida mientras caminas.'}</p>
    </section>
    <AppDialog open={outsideDialog==='continue'} title="Estás fuera del territorio" onClose={cancelOutside}><div className="space-y-5"><div className="flex items-start gap-3 rounded-2xl bg-[#fff7e2] p-4 text-[#704f00]"><MapPinOff className="mt-0.5 shrink-0"/><p>El GPS detectó que estás fuera del área asignada en Pereira. Puedes continuar y, al finalizar, te preguntaremos si deseas guardar esta ruta.</p></div><div className="grid grid-cols-2 gap-3"><button className="focus-ring min-h-12 rounded-xl border border-[#cfd9e8] font-bold" onClick={cancelOutside}>Cancelar</button><button className="focus-ring min-h-12 rounded-xl bg-[#2f63b8] font-bold text-white" onClick={continueOutside}>Sí, continuar</button></div></div></AppDialog>
    <AppDialog open={outsideDialog==='save'} title="¿Guardar ruta externa?" onClose={()=>setOutsideDialog(null)}><div className="space-y-5"><div className="flex items-start gap-3 rounded-2xl bg-[#fff7e2] p-4 text-[#704f00]"><MapPinOff className="mt-0.5 shrink-0"/><p>Una parte o toda la ruta está fuera del territorio objetivo. ¿Deseas guardarla de todas maneras?</p></div><div className="grid grid-cols-2 gap-3"><button className="focus-ring min-h-12 rounded-xl border border-[#cfd9e8] font-bold" onClick={()=>setOutsideDialog(null)}>No guardar</button><button className="focus-ring min-h-12 rounded-xl bg-[#0c2347] font-bold text-white disabled:opacity-60" disabled={saving} onClick={()=>{setOutsideDialog(null);void persistRoute()}}>{saving?'Guardando…':'Sí, guardar'}</button></div></div></AppDialog>
  </main>;
}
