'use client';
import {useEffect,useState} from 'react';
import {allRows,csv,downloadFile} from '@/lib/reports';
import {MapPoint,RouteRecord} from '@/lib/mapData';
import {isInsideTerritory,totalDistance} from '@/lib/geoUtils';
export default function ReportsPanel({points,routes}:{points:MapPoint[];routes:RouteRecord[]}){
 const [cultos,setCultos]=useState<Record<string,unknown>[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false);
 useEffect(()=>{void allRows('historial_cultos').then(data=>{setCultos(data);setLoaded(true)}).catch(e=>setMessage(e.message))},[]);
 async function backup(){setBusy(true);setMessage('');try{const tables=['puntos_mapa','rutas_evangelizadas','historial_cultos','seguimiento_amigos'];const data=Object.fromEntries(await Promise.all(tables.map(async t=>[t,await allRows(t)])));downloadFile(`respaldo-ipuic-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,exportado_en:new Date().toISOString(),...data},null,2),'application/json')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo exportar.')}finally{setBusy(false)}}
 const months=Array.from(new Set(cultos.map(c=>String(c.fecha_culto).slice(0,7)))).sort().reverse();
 return <div className="space-y-4"><div className="grid grid-cols-2 gap-3">{[['Hermanos',points.filter(p=>p.tipo==='hermano_verde').length],['Amigos',points.filter(p=>p.tipo==='amigo_rojo').length],['Lugares de culto',points.filter(p=>p.tipo==='culto_azul').length],['Cultos realizados',loaded?cultos.length:'…'],['Km registrados',(routes.reduce((s,r)=>s+totalDistance(r.path),0)/1000).toFixed(2)],['Rutas externas',routes.filter(r=>r.path.some(p=>!isInsideTerritory(p))).length]].map(([name,count])=><div key={name} className="rounded-xl bg-[#eef4fc] p-3"><p className="text-sm">{name}</p><strong className="text-2xl">{count}</strong></div>)}</div><p className="text-sm text-[#5f6f86]">Los kilómetros incluyen recorridos repetidos; no representan calles únicas cubiertas.</p><h3 className="font-bold">Asistencia por mes</h3>{loaded&&!months.length&&<p>No hay cultos registrados.</p>}{months.map(month=><p key={month} className="flex justify-between border-b py-2"><span>{month}</span><strong>{cultos.filter(c=>String(c.fecha_culto).startsWith(month)).reduce((n,c)=>n+Number(c.asistentes),0)} asistencias</strong></p>)}<p className="text-sm">Las asistencias son la suma de reuniones, no personas únicas.</p><button disabled={busy} className="min-h-12 w-full rounded-xl bg-[#2f63b8] px-3 font-bold text-white" onClick={backup}>{busy?'Preparando…':'Descargar respaldo completo (JSON)'}</button><div className="flex flex-wrap gap-2">{[['Personas y lugares','puntos_mapa'],['Rutas','rutas_evangelizadas'],['Cultos','historial_cultos'],['Visitas','seguimiento_amigos']].map(([label,table])=><button key={table} disabled={busy} className="rounded-xl border p-3 text-sm" onClick={async()=>{setBusy(true);try{downloadFile(`${table}.csv`,csv(await allRows(table)),'text/csv;charset=utf-8')}catch(e){setMessage(String(e))}finally{setBusy(false)}}}>{label} · CSV</button>)}</div><p className="text-sm text-[#5f6f86]">Los archivos contienen información privada. El respaldo incluye enlaces a fotos, no los archivos de imagen. CSV se abre en Excel.</p>{message&&<p role="alert" className="text-red-700">{message}</p>}</div>
}
