'use client';
import {useEffect,useState} from 'react';
import {getSupabase} from '@/lib/supabase';
import {allRows} from '@/lib/reports';
type Photo={path:string;size:number;url:string};
export default function StoragePanel(){const [photos,setPhotos]=useState<Photo[]>([]),[used,setUsed]=useState<Set<string>>(new Set()),[message,setMessage]=useState('Cargando archivos…'),[busy,setBusy]=useState(false);
 async function references(){const rows=(await Promise.all([allRows('puntos_mapa'),allRows('historial_cultos')])).flat();return new Set(rows.flatMap(r=>(r.fotos_urls as string[])??[]))}
 async function load(){try{const bucket=getSupabase().storage.from('fotos-cultos');const result:Photo[]=[];async function scan(prefix:string){for(let offset=0;;offset+=100){const {data,error}=await bucket.list(prefix,{limit:100,offset,sortBy:{column:'name',order:'asc'}});if(error)throw error;for(const item of data){const path=prefix?`${prefix}/${item.name}`:item.name;if(item.id)result.push({path,size:Number(item.metadata?.size??0),url:bucket.getPublicUrl(path).data.publicUrl});else await scan(path)}if(data.length<100)break}}await scan('');setPhotos(result);setUsed(await references());setMessage('')}catch{setMessage('No se pudo consultar el almacenamiento. Reintenta al tener conexión.')}}
 useEffect(()=>{void load()},[]);
 async function remove(photo:Photo){if(!window.confirm('¿Eliminar definitivamente esta foto sin referencias? Esta acción no se puede deshacer.'))return;setBusy(true);try{if((await references()).has(photo.url))throw new Error('La foto está vinculada a un registro y no se eliminará.');const {error}=await getSupabase().storage.from('fotos-cultos').remove([photo.path]);if(error)throw error;setPhotos(p=>p.filter(f=>f.path!==photo.path));setMessage('Foto eliminada definitivamente.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo eliminar.')}finally{setBusy(false)}}
 const bytes=photos.reduce((n,p)=>n+p.size,0);return <div className="space-y-4"><p className="text-2xl font-bold">{(bytes/1024/1024).toFixed(2)} MB en fotos</p><p>{photos.length} archivos en fotos-cultos</p><p className="text-sm">Solo se muestran para limpieza los archivos sin referencias en personas, lugares o bitácoras. Revisa cada imagen antes de borrarla.</p>{message&&<p role="status">{message}</p>}<button className="rounded-xl border p-3" onClick={load}>Actualizar</button><div className="grid grid-cols-2 gap-3">{photos.filter(p=>!used.has(p.url)).map(p=><div className="rounded-xl border p-3" key={p.path}><img className="h-24 w-full rounded-xl object-cover" src={p.url} alt="Foto sin referencia"/><p className="my-2 text-sm">{Math.round(p.size/1024)} KB</p><button disabled={busy} onClick={()=>remove(p)} className="text-sm font-bold text-red-700">Eliminar archivo</button></div>)}</div></div>}
