'use client';
import {FormEvent,useEffect,useState} from 'react';
import {getSupabase} from '@/lib/supabase';
export default function UsersPanel(){const [users,setUsers]=useState<{id:string;nombre_completo:string;rol:string;bloqueado:boolean}[]>([]),[message,setMessage]=useState('Cargando…'),[busy,setBusy]=useState(false),[admin,setAdmin]=useState(false),[current,setCurrent]=useState('');
 const [name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState('');
 async function load(){const db=getSupabase();const {data:{user}}=await db.auth.getUser();if(!user)return;setCurrent(user.id);const {data,error}=await db.from('perfiles').select('id,nombre_completo,rol,bloqueado');if(error){setMessage('No se pudieron cargar los usuarios.');return}setUsers(data);setAdmin(data.some(p=>p.id===user.id&&p.rol==='admin'&&!p.bloqueado));}
 useEffect(()=>{void load().then(()=>setMessage(''))},[]);
 async function invoke(body:Record<string,unknown>){const {data,error}=await getSupabase().functions.invoke('manage-users',{body});if(error){const detail=await error.context?.json?.().catch(()=>null);throw new Error(detail?.error??'No se pudo completar la gestión de cuentas.')}if(data?.error)throw new Error(data.error)}
 async function create(event:FormEvent){event.preventDefault();setBusy(true);try{await invoke({action:'create',name,username,password});setPassword('');setUsername('');setName('');await load();setMessage('Usuario creado como evangelizador. Puedes cambiar su rol en la lista.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo crear el usuario.')}finally{setBusy(false)}}
 async function block(id:string,blocked:boolean){if(!window.confirm(blocked?'¿Bloquear el acceso de este usuario?':'¿Restablecer el acceso de este usuario?'))return;setBusy(true);try{await invoke({action:'block',id,blocked});await load();setMessage(blocked?'Usuario bloqueado.':'Usuario habilitado.')}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function change(id:string,rol:string){if(!window.confirm('¿Cambiar los permisos de este usuario?'))return;setBusy(true);try{const {error}=await getSupabase().from('perfiles').update({rol}).eq('id',id).select('id').single();if(error)throw error;setUsers(u=>u.map(p=>p.id===id?{...p,rol}:p));setMessage('Permisos actualizados.')}catch{setMessage('Solo un administrador puede actualizar los permisos.')}finally{setBusy(false)}}
 return <div className="space-y-4"><p>Cada persona puede ingresar con su propio usuario y contraseña. Los roles se aplican en la base de datos.</p>{message&&<p role="status">{message}</p>}{admin&&<form onSubmit={create} className="space-y-3 rounded-xl bg-[#eef4fc] p-3"><h3 className="font-bold">Crear usuario</h3><label className="block">Nombre completo<input className="block min-h-12 w-full rounded-xl border px-3" value={name} onChange={e=>setName(e.target.value)} required maxLength={150}/></label><label className="block">Usuario<input className="block min-h-12 w-full rounded-xl border px-3" value={username} onChange={e=>setUsername(e.target.value)} required pattern="[a-zA-Z0-9._-]{3,40}" autoCapitalize="none"/></label><label className="block">Contraseña inicial<input className="block min-h-12 w-full rounded-xl border px-3" value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="new-password" required minLength={10} maxLength={100}/></label><p className="text-sm">La persona podrá cambiarla al ingresar. Mínimo 10 caracteres.</p><button disabled={busy} className="min-h-12 rounded-xl bg-[#2f63b8] px-4 font-bold text-white">Crear cuenta</button></form>}{users.map(u=><div key={u.id} className="rounded-xl border p-3"><strong>{u.nombre_completo.replace('@usuarios.casaoracion.local','')}{u.bloqueado?' · Bloqueado':''}</strong><select aria-label={`Rol de ${u.nombre_completo}`} disabled={!admin||busy||u.id===current} className="mt-2 min-h-12 w-full rounded-xl border px-3" value={u.rol} onChange={e=>void change(u.id,e.target.value)}><option value="admin">Administrador</option><option value="lider">Líder</option><option value="evangelizador">Evangelizador</option></select>{admin&&u.id!==current&&<button disabled={busy} className="mt-2 min-h-11 px-3 text-red-700" onClick={()=>block(u.id,!u.bloqueado)}>{u.bloqueado?'Habilitar acceso':'Bloquear acceso'}</button>}</div>)}<p className="text-sm text-[#5f6f86]">Administrador: gestiona permisos. Líder: administra registros. Evangelizador: modifica sus propios puntos y rutas. Tu propio rol no se cambia aquí.</p></div>}
